using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("DogStatsD for C#")]
[assembly: AssemblyDescription("A C# DogStatsD client")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Datadog")]
[assembly: AssemblyProduct("StatsdClient")]
[assembly: AssemblyCopyright("Copyright ©  2015")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

[assembly: ComVisible(false)]

[assembly: Guid("ecebfa48-5557-4fe6-84a6-c0b1e3ece14c")]

// The following lines were generated by Nearmap build script:
[assembly: AssemblyVersion("1.1.18019.0")]
[assembly: AssemblyFileVersion("1.1.18019-sha-294fe71")]
[assembly: AssemblyInformationalVersion("1.1.18019-sha-294fe71")]
[assembly: AssemblyMetadata("Package", "2018.01.18.20.50.29-nearmap-2.x-1.1.18019-sha-294fe71.294fe7140ead9f1655a23b21bc6723e9da2a0849")]
[assembly: AssemblyMetadata("Branch","nearmap-2.x")]
[assembly: AssemblyMetadata("Sha", "294fe7140ead9f1655a23b21bc6723e9da2a0849")]
